### ISSUE TITLE
 communicate with Allen Bradley Micro850

### ISSUE THREAD

**Issue by PatriceSim** [ornl-epics/etherip#22]
Hi, I like to use this driver for communicate with Allen Bradley Micro850. The bigest difference with a CompactLogix is the Micro850 doesn't have slot number. I found in other driver the connection path is ConnectionPath = [0x20, 0x02, 0x24, 0x01] not ConnectionPath = [0x01, self.ProcessorSlot, 0x20, 0x02, 0x24, 0x01] like CompactLogix. I don't have many experience with java programation but do you think this program need many modification to be able to communicate?

**Comment by dmroeder** [comment]
There are 3 main differences, at least from what I'm remembering.
1) The connection path is missing the first 2 bytes as mentioned
2) Strings are handled a little different
3) There are additional data types (Long Real and unsigned words)

**Comment by kasemir** [comment]
Do you have a Micro850 to try this?
Modify the driver to for example recognize `slot=-1` as a flag to omit the slot from the connection path, and see if that works.

**Comment by ZootHii** [comment]
Is there anyone who tried with Allen Bradley Micro8XX, does it work?

**Comment by dmroeder** [comment]
Did you set the micro800 flag?
comm.Micro800 = True
