### ISSUE TITLE
it may block here when the ethernetip server never reply

### ISSUE THREAD

**Issue by zwh6611** [ornl-epics/etherip#28]
public void read(final ProtocolDecoder decoder) throws Exception
    {
        // Read until protocol has enough data to decode
        this.buffer.clear();
        do
        {
            this.channel.read(this.buffer).get(this.timeout_ms, MILLISECONDS);
        }
        while (this.buffer.position() < decoder.getResponseSize(this.buffer));

---------------------------------------------------> I fix that by the code below
        int readTryCount = 0;
        do
        {
            readTryCount++;
            if(readTryCount >= maxReadTryCount){
                throw new TimeoutException("read time out");
            }
            this.channel.read(this.buffer).get(this.timeout_ms, MILLISECONDS);
        }
        while (this.buffer.position() < decoder.getResponseSize(this.buffer));

**Comment by kasemir** [comment]
Thanks, has been added in 190fa76f1e3a285cd3a5351ff242219ea124006c
