### ISSUE TITLE
Request for RSWho like capability

### ISSUE THREAD

**Issue by guyit** [ornl-epics/etherip#3]
Dear developer,
Great piece of code!

I'm looking for a java code that simulates RSWho. In other words I'm looking for an application that broadcast a "CIP-ping" request (similar to what RSWho does) and get a list of all Rockwell PLCs includes its device info (such as device name, type, version etc).
I know this currently does not exist but I wonder if it is something you can developed?

Thanks

**Comment by kasemir** [comment]
Sorry, I don't see spare cycles for adding CIP-ping support in the foreseeable future.
If you want to add that, I'll welcome pull requests.

**Comment by kasemir** [comment]
Closed due to inactivity
