### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by codepitbull** [ornl-epics/etherip#46]
Hey, I just checked out your library and tried building it locally.
Sadly the tests fail:

```
[ERROR] Failures: 
[ERROR]   SendRRDataTest.testSendRRData:52 
Expected: "0000 - 6F 00 18 00 00 71 02 12 00 00 00 00 30 30 30 30 - o....q......0000\n0010 - 30 30 30 31 00 00 00 00 00 00 00 00 00 00 02 00 - 0001............\n0020 - 00 00 00 00 B2 00 08 00 0E 03 20 01 24 01 30 07 - .......... .$.0.\n"
     but: was "0000 - 6F 00 18 00 00 71 02 12 00 00 00 00 30 30 30 30 - o....q......0000\n0010 - 30 30 30 43 00 00 00 00 00 00 00 00 00 00 02 00 - 000C............\n0020 - 00 00 00 00 B2 00 08 00 0E 03 20 01 24 01 30 07 - .......... .$.0.\n"
```

I testes with JDK 8, 11 and 21, same result for all of them.

Any idea what might go wrong?

Cheers,
Jochen

**Comment by kasemir** [comment]
The test runs fine on its own, but not within a sequence of tests because the "context" counts up from `00000001` (hex 30 30 30 30 30 30 30 31).

Will look at updating the test so that it resets the context counter.

**Comment by kasemir** [comment]
Updated tests to reset the "context" counter, 0e6c28d5c56a367e9dba0acd7eb0172df8d9a82d.
Now all tests pass for me.

**Comment by codepitbull** [comment]
Nice! Just came back to report that :D 
Thank you for the quick fix!

**Comment by codepitbull** [comment]
Verified, tests are working.
And thanks for updating the JDK, was already preparing a PR :)
