### ISSUE TITLE
Update to JUnit 5 and AssertJ

### ISSUE THREAD

**Issue by codepitbull** [ornl-epics/etherip#47]
Are you interested in a PR to update tests to use JUnit 5 ?
I would also offer to replace Hamcrest with AssertJ (nicer, more readable fluent assertions, https://assertj.github.io/doc/), but that one would completely up to you if you want it :)

**Comment by kasemir** [comment]
Sure, update to JUnit 5 would be good.

As for ham crest or assertj, I'd prefer to avoid both and keep the dependencies minimal.
In the end,
```
import static org.junit.jupiter.api.Assertions.assertEquals;
...
assertEquals("Foo", test_string);
```
is really sufficient.

Or if we feel really sophisticated, then
```
assertEquals("Foo", test_string, "Didn’t get expected result");
```

**Comment by kasemir** [comment]
Just updated to JU5 and removed the hamcrest dependency, thanks for the suggestion!
